### ISSUE TITLE
Did @gjaldon stop maintaining library?

### ISSUE THREAD

**Issue by sofakingworld** [gjaldon/ecto_enum#111]
There are several PRs that waits for feedback

People spend time improving the library, ignoring them is disrespectful

**Comment by emaiax** [comment]
@sofakingworld It'd be very nice if you'd fork this and publish as a maintained package :D

**Comment by gjaldon** [comment]
@sofakingworld thank you for the contribution. Would like to remind, however, that this project is not sponsored by any company or individual and is provided for free. I will review the PRs when I am able to make time for it given I have other commitments. I think making demands out of people's time is quite rude especially considering I do not owe you anything. You could have reached out to me on #elixir-slack instead and asked nicely. No need for toxicity

Will be closing this PR

**Comment by sofakingworld** [comment]
@gjaldon This issue just for clarify the situation. I'm not toxic, sorry, that's all about not good english knowledge by me.

So, do you continue maintaining, or we fork and maintain by community?
