### ISSUE TITLE
Clearer error message for invalid enum value

### ISSUE THREAD

**Issue by gjaldon** [gjaldon/ecto_enum#13]
From: https://elixirforum.com/t/ectoenum-for-activerecord-like-enums-in-ecto-updated/1264/3?u=gjaldon

I feel like this example:

iex> Repo.insert!(%User{status: :none})
*\* (Elixir.EctoEnum.Error) :none is not a valid enum value
Should include the enum type in the error message. Something like: :none is not a valid enum value for StatusEnum

But good work! Would like to see this working for Ecto 2.0 as well!

**Comment by yordis** [comment]
Should we use `validate_inclusion` for make sure that it doesn't blow up before insert? I tried but it seems to do not work as I expected, I guess it fails when create the schema (because the casting)

Should we just use that validation?

**Comment by ryanwinchester** [comment]
should it be like this?

```elixir
  def changeset(%__MODULE__{} = entry, attrs) do
    entry
    |> cast(attrs, @required_fields ++ @optional_fields)
    |> validate_required(@required_fields)
    |> validate_inclusion(:entry_type, EntryTypeEnum.__valid_values__())
    |> validate_inclusion(:element_type, ElementTypeEnum.__valid_values__())
  end
```

**Comment by gjaldon** [comment]
A `validate_enum` helper now comes with EctoEnum with this PR https://github.com/gjaldon/ecto_enum/pull/53. The error message was already fixed

**Comment by yordis** [comment]
@gjaldon before you put in `prod` I left a comment about the PR

**Comment by gjaldon** [comment]
@yordis thanks for the comment! I'm in the process of refactoring it to use `Ecto.Changeset.validate_change/4` so we add metadata for this validator.

**Comment by yordis** [comment]
@gjaldon just dont forget the `validation: ` key 😄
