### ISSUE TITLE
Ecto 2.0 support

### ISSUE THREAD

**Issue by gjaldon** [gjaldon/ecto_enum#15]

**Comment by slashmili** [comment]
I'm using cto_enum with Ecto 2.0 and everything seem works fine.
What problem do you have with Ecto 2.0?

**Comment by asiniy** [comment]
@slashmili it can't be installed because of conflicts :smile:

**Comment by slashmili** [comment]
I added to my dependency list a month ago (version `0.3.1`) and there was no limitation. I'm just asking if I should expect some bugs? what was the reason that it current version doesn't support Ecto 2.0

**Comment by asiniy** [comment]
@slashmili yeah, I'm little bit frustrated by this limitation too

**Comment by mtwilliams** [comment]
`Ecto.Storage` in the test helpers, for one.

**Comment by Eiji7** [comment]
Do you support [prefix](https://github.com/elixir-ecto/ecto/issues/1005) in `create_type` and `drop_type`?

**Comment by rlopzc** [comment]
+1, is this working now?

**Comment by shakthimaan** [comment]
```
$ mix deps.get 
Running dependency resolution

Failed to use "ecto" (version 2.0.5) because
  ecto_enum (version 0.4.0) requires >= 0.13.1 and ~> 1.1.0
  phoenix_ecto (version 3.0.1) requires ~> 2.0
  Locked to 2.0.5 in your mix.lock

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

Any suggestions?

**Comment by mtwilliams** [comment]
As far as I know the runtime portion works. In that case, you can just `override` to force `ecto ~> 2.0.5`.

**Comment by shakthimaan** [comment]
What is required to get a clean dependency resolution without the override?

**Comment by gjaldon** [comment]
Finally released https://github.com/gjaldon/ecto_enum/releases/tag/v1.0!
