### ISSUE TITLE
Compatible with Ecto.Changeset?

### ISSUE THREAD

**Issue by shawnbro** [gjaldon/ecto_enum#29]
Just imported this in to my Phoenix project, added `import EctoEnum` to my model, tried to run my test suite and got the following error:

`function cast/3 imported from both EctoEnum and Ecto.Changeset, call is ambiguous`.

Any idea how to solve this?

**Comment by shawnbro** [comment]
Solved by just explicitly calling `Ecto.Changeset.cast` in my changeset method.

**Comment by gjaldon** [comment]
@shawnbro better to not import `EctoEnum` into your model since I think it's more likely you'll use `Ecto.Changeset` functions than `EctoEnum` ones in your model.

**Comment by shawnbro** [comment]
Thank you.  I misread the docs about where it should be imported.
