### ISSUE TITLE
Ecto 2.1 support

### ISSUE THREAD

**Issue by arnodirlam** [gjaldon/ecto_enum#31]
[Ecto 2.1](https://github.com/elixir-ecto/ecto/releases/tag/v2.1.0) just came out and I wonder if it will be supported soon by ecto_enum?

**Comment by asgoel** [comment]
+1. There are some features of Ecto 2.1 that I'd really like to use but this is currently holding me back.

**Comment by imranismail** [comment]
This is just a version bump right?

**Comment by gjaldon** [comment]
Just released EctoEnum 1.0.1 which has Ecto 2.1 support. No huge change but at least removes the need for using override in mix.exs.
