### ISSUE TITLE
Preloading association with embedded schema/enum type fails

### ISSUE THREAD

**Issue by madshargreave** [gjaldon/ecto_enum#35]
Hi

Say I have a query like this

```
def find_identity_conversation(identity, conversation_id) do
    query =
      from c in Conversation,
      preload: [:messages]
  end
```

If the `messages` association embeds a struct (here `MessagePart`) with an enum type like so

```
defmodule MessagePart do
   defenum TypeEnum, [text: "text", image: "image", emoji: "emoji"]

   embedded_schema do
       field :type, TypeEnum
   end
   ...
````

it fails with 

```
** (ArgumentError) cannot load `"texts"` as type Messenger.MessagePart.TypeEnum for :type in schema Messenger.MessagePart
```

**Comment by gjaldon** [comment]
Can you share the project you're working on so I can reproduce the error? If not, can you provide the relevant code to reproduce this? (the models and their migrations)

**Comment by vyorkin** [comment]
is there any reason / does it make any sense to use ecto_enum in embedded_schema?

**Comment by gjaldon** [comment]
@vyorkin didn't realize he was using `embedded_schema`. We can't use ecto_enum with embedded schema and there doesn't seem to be any reason to do it.
