### ISSUE TITLE
Creating Postgres Enum types inside a schema

### ISSUE THREAD

**Issue by brandonparsons** [gjaldon/ecto_enum#42]
Currently the `create_type/0` function adds the enum types inside Postgres' `public` schema: https://github.com/gjaldon/ecto_enum/blob/01a1f0cc3cc528eabf152ede5f4bcf3bddd866b1/lib/ecto_enum/postgres.ex#L42

Would it be possible to extend this to create the enum types inside other schemas?

**Comment by gjaldon** [comment]
@brandonparsons yes it is. Let me work on that over the weekend. Should be a simple change.
