### ISSUE TITLE
Documentation on how to update an existing enum to have more types

### ISSUE THREAD

**Issue by boddhisattva** [gjaldon/ecto_enum#54]
Hello,

Thank you for your work on this package :). It's seems to be working well for us so far. Can you kindly let us know how we can add more types to an existing enum in my app given that we've already built the initial enum using the steps mentioned as part of the README. I tried updating my `ecto_enums.ex` to specify more enum types wrt a particular enum field but it clearly looks like we have to have some migrations around this from what I found as part of [this SO answer](https://stackoverflow.com/questions/1771543/postgresql-updating-an-enum-type/7834949#7834949)

**Comment by gjaldon** [comment]
Does this cover it for you?
https://github.com/gjaldon/ecto_enum#postgres

**Comment by boddhisattva** [comment]
Thank you @gjaldon! and I'm sorry for missing this. I'm thinking would you want make this clearer in the README with specifying something like `How to add or remove more enum types` ? I think it may help.
