### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by axelson** [gjaldon/ecto_enum#58]
Is it possible to cut a new release that includes `MyEnum.valid_value?`? I'd like to use it to do validation on a changeset before getting to the DB.

**Comment by tlvenn** [comment]
@gjaldon any chance to get this done please ?

**Comment by bencates** [comment]
Thirding this request, and also please consider merging #50 as well.

@gjaldon, I don't want to overstep, but if you're not interested in maintaining this project anymore my company (github.com/system76) would be more than happy to take the maintenance burden off your shoulders.

**Comment by brandonparsons** [comment]
@gjaldon Hi there - jumping in here too. Possible to cut a new release?

**Comment by erikreedstrom** [comment]
@gjaldon Is this repo being retired?

**Comment by brandonparsons** [comment]
@bencates It looks like @gjaldon hasn't made any commits (to anything) since July. I'd be surprised if he continues to maintain this. Probably a good time for you to fork and continue if you are still willing...

**Comment by S1r-Lanzelot** [comment]
@brandonparsons @bencates  Please see here: https://github.com/gjaldon/ecto_enum/issues/66

**Comment by gjaldon** [comment]
This should be addressed in the latest release https://hex.pm/packages/ecto_enum/1.2.0. Let me know if it's still a problem
