### ISSUE TITLE
Is ecto_enum still maintained?

### ISSUE THREAD

**Issue by axelson** [gjaldon/ecto_enum#66]
@gjaldon It's been nearly a year since the previous release of ecto_enum and 10 months since https://github.com/gjaldon/ecto_enum/pull/53 was merged with a new feature. Are you still planning to maintain ecto_enum? If not, then would you be willing to bless a fork (or transfer ownership)?

**Comment by S1r-Lanzelot** [comment]
I tweeted at @gjaldon to see what's up... Still radio silence.

**Comment by gjaldon** [comment]
I’ll cut a release and look into adding a collaborator over the weekend.

**Comment by jeremyjh** [comment]
@gjaldon bump, we would really appreciate a release!

**Comment by gjaldon** [comment]
Just cut a new release https://hex.pm/packages/ecto_enum/1.2.0
