### ISSUE TITLE
Changeset errors instead of Error raise

### ISSUE THREAD

**Issue by Troush** [gjaldon/ecto_enum#7]
Hey, thank you for great repo !

On my thoughts that it would be better if ecto_enum would store it error in `changeset.errors` instead of Error raise. Because save this error in changeset is more convenient way to handle data validity errors in Ecto.

What do you think about it?

**Comment by gjaldon** [comment]
@Troush I thinks this would be great! Feel free to send a PR. :) If you don't have time, let me know and I'll work on it in the next days.

**Comment by Troush** [comment]
Will try to do this on upcoming weekdays.

**Comment by gjaldon** [comment]
@Troush oops! I just addressed this with my latest commits I pushed several hours ago. :D Closing this issue now :) Try out the latest release and let me know if everything is in order. ;)

**Comment by Troush** [comment]
This is even better! xD
Thnx!
