### ISSUE TITLE
Publish a new release with formatter config included

### ISSUE THREAD

**Issue by sheharyarn** [gjaldon/ecto_enum#70]
You're already exporting `locals_without_parens` in your [`formatter.exs`](https://github.com/gjaldon/ecto_enum/blob/master/.formatter.exs) config, but there isn't a published release from which elixir applications can import the config so we still have to manually write them.

Once a new release is published with the config, we'll only need to add this to our formatter.exs:

```elixir
import_deps: [:ecto, :ecto_enum],
```

Awesome package btw!

**Comment by gjaldon** [comment]
Hi @sheharyarn. Just updated the package:
https://hex.pm/packages/ecto_enum/1.2.0
https://github.com/gjaldon/ecto_enum/releases

Thanks for reporting the issue
